---
title: "Format the Asembo enteric antibody data"
output: 
  html_document:
    theme: default
    highlight: haddock
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
---

# Summary

This script loads the raw data and formats it for all of the analyses

# Script preamble
```{r preamble}
#-----------------------------
# preamble
#-----------------------------
rm(list=ls())
library(tidyverse)
library(lubridate)


```


#Load and format the data

```{r data format}
#-----------------------------
# load the data
#-----------------------------

d <- readRDS("~/dropbox/asembo/data/final/asembo_sero.rds")

# exclude 6 measurements with missing age 
d <- d %>%
  filter(!is.na(age))

# list the enteric antigens and make formatted labels for them
mbavars <- c("vsp3","vsp5","cp17","cp23","leca","salb","sald","etec","cholera","p18","p39")

mbalabs <- c("Giardia VSP-3","Giardia VSP-5","Cryptosporidium Cp17","Cryptosporidium Cp23","E. histolytica LecA","Salmonella LPS group B","Salmonella LPS group D","ETEC LT B subunit","Cholera toxin B subunit","Campylobacter p18","Campylobacter p39")


#-----------------------------
# reshape long and convert
# to log10 values
#-----------------------------
dl <- d %>%
  select(childid,time,mdate,sex,age,tr,mbavars) %>%
  gather(antigen,mfi,-childid,-time,-mdate,-sex,-age,-tr)

# set negative and zero values to 1 before the log10 transform
dl <- dl %>%
  mutate(mfi = ifelse(mfi<=0,1,mfi),
         logmfi = log10(mfi),
         antigen=factor(antigen,levels=mbavars)
  )

#-----------------------------
# calculate the difference in 
# MFI values within children  
# longitudinally
# to look at increases and decreases
#-----------------------------
dmfidiff <- dl %>%
  select(childid,antigen,time,logmfi) %>%
  spread(time,logmfi) %>%
  filter(!is.na(A) & !is.na(B)) %>%
  mutate(logmfidiff = B-A) %>%
  select(childid,antigen,logmfidiff)
dl <- left_join(dl,dmfidiff,by=c("childid","antigen"))

#-----------------------------
# calculate the difference in age (months)
# for person-time of observation
#-----------------------------
dagediff <- dl %>%
  select(childid,antigen,time,age) %>%
  spread(time,age) %>%
  filter(!is.na(A) & !is.na(B)) %>%
  mutate(agediff = B-A) %>%
  select(childid,antigen,agediff)
dl <- left_join(dl,dagediff,by=c("childid","antigen"))

#-----------------------------
# group antigens by pathogen
# for plot aesthetics
# label antigens with fancier names
#-----------------------------
dl$pathogen <- NA
dl$pathogen[dl$antigen %in% c("vsp3","vsp5")] <- "Giardia"
dl$pathogen[dl$antigen %in% c("cp17","cp23")] <- "Cryptosporidium"
dl$pathogen[dl$antigen %in% c("leca")] <- "E. histolytica"
dl$pathogen[dl$antigen %in% c("salb","sald")] <- "Salmonella"
dl$pathogen[dl$antigen %in% c("etec")] <- "ETEC"
dl$pathogen[dl$antigen %in% c("cholera")] <- "V. cholerae"
dl$pathogen[dl$antigen %in% c("p18","p39")] <- "Campylobacter"

dl <- dl %>%
  mutate(pathogen = factor(pathogen,levels=c("Giardia","Cryptosporidium","E. histolytica","Salmonella","ETEC","V. cholerae","Campylobacter")),
         antigenf=factor(antigen,levels=mbavars,labels=mbalabs)) %>%
  select(pathogen,antigen,antigenf,childid,time,mdate,sex,age,agediff,tr,mfi,logmfi,logmfidiff)
     
#-----------------------------
# reformat measurement date
# to year and week of the year
# to more completely de-identify
# the data
#-----------------------------
dl <- dl %>%
  mutate(year=year(mdate),
         month=month(mdate),
         week=week(mdate)) %>%
  select(pathogen,antigen,antigenf,childid,time,year,month,week,sex,age,agediff,tr,mfi,logmfi,logmfidiff)

#-----------------------------
# save a long version of the
# dataset for all future 
# analyses
#-----------------------------
saveRDS(dl,file="~/enterics-seroepi/data/asembo_analysis.rds")
write_csv(dl,path="~/enterics-seroepi/data/asembo_analysis.csv")
```
# Session Info
```{r session info}
sessionInfo()
```




