---
title: "Format the Leogane, Haiti enteric antibody data"
output: 
  html_document:
    theme: default
    highlight: haddock
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
---

# Summary

This script loads the raw data and formats it for all of the analyses

# Script preamble
```{r preamble}
#-----------------------------
# preamble
#-----------------------------
library(here)
here()

library(tidyverse)
library(lubridate)
library(foreign)


```


#Load and format the data

```{r data format}
#-----------------------------
# load the data
#-----------------------------

d <- read.dta("~/dropbox/haiti2/data/final/haiti2-long.dta")

# recode one incorrect sampleid
d$sampleid[d$sampleid=="B7"] <- "3"

# rename one antigen and a few vars
d <- d %>% rename(vsp3=vsp3s,sdate=sampledate,age=agey)

#----------------------------------
# list the enteric antigens and 
# make formatted labels for them
#----------------------------------
mbavars <- c("vsp3","vsp5","cp17","cp23","leca","salb","sald","etec","norogi","norogii")

mbalabs <- c("Giardia VSP-3","Giardia VSP-5","Cryptosporidium Cp17","Cryptosporidium Cp23","E. histolytica LecA","Salmonella LPS group B","Salmonella LPS group D","ETEC LT B subunit","Norovirus GI.4","Norovirus GII.4.NO")

#-----------------------------
# filter to just the relevant
# variables
#-----------------------------
d2 <- d %>% 
  select(id,sampleid,sdate,age,mbavars)



#-----------------------------
# reshape long and convert
# to log10 values
#-----------------------------
dl <- d2 %>%
  gather(antigen,mfi,-id,-sampleid,-sdate,-age)

# set negative and zero values to 1 before the log10 transform
dl <- dl %>%
  mutate(mfi = ifelse(mfi<=0,1,mfi),
         logmfi = log10(mfi))


#-----------------------------
# group antigens by pathogen
# for plot aesthetics
# label antigens with fancier names
#-----------------------------
dl$pathogen <- NA
dl$pathogen[dl$antigen %in% c("vsp3","vsp5")] <- "Giardia"
dl$pathogen[dl$antigen %in% c("cp17","cp23")] <- "Cryptosporidium"
dl$pathogen[dl$antigen %in% c("leca")] <- "E. histolytica"
dl$pathogen[dl$antigen %in% c("salb","sald")] <- "Salmonella"
dl$pathogen[dl$antigen %in% c("etec")] <- "ETEC"
dl$pathogen[dl$antigen %in% c("norogi","norogii")] <- "Norovirus"


dl <- dl %>%
  mutate(pathogen = factor(pathogen,levels=c("Giardia","Cryptosporidium","E. histolytica","Salmonella","ETEC","Norovirus")),
         antigenf=factor(antigen,levels=mbavars,labels=mbalabs)) %>%
  select(pathogen,antigen,antigenf,id,sampleid,sdate,age,mfi,logmfi)
     
#-----------------------------
# reformat measurement date
# to year and week of the year
# to more completely de-identify
# the data
#-----------------------------
dl <- dl %>%
  mutate(year=year(sdate),
         month=month(sdate),
         week=week(sdate)) %>%
  select(pathogen,antigen,antigenf,id,sampleid,year,month,week,age,mfi,logmfi)

#-----------------------------
# save a long version of the
# dataset for all future 
# analyses
#-----------------------------
saveRDS(dl,file=here::here("data","haiti_analysis.rds"))
write_csv(dl,path=here::here("data","haiti_analysis.csv"))
```
# Session Info
```{r session info}
sessionInfo()
```




