---
title: "Format the Kongwa enteric antibody data"
output: 
  html_document:
    theme: default
    highlight: haddock
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
---

# Summary

This script loads the raw data and formats it for all of the analyses

# Script preamble
```{r preamble}
#-----------------------------
# preamble
#-----------------------------
library(here)
here()

library(tidyverse)


```


#Load and format the data

```{r data format}
#-----------------------------
# load the data
# note: this is an external
# dataset and not in the
# current repository
#-----------------------------

d <- readRDS("~/dropbox/kongwa/data/final/kongwa-mba-kids.rds")

# list the enteric antigens and make formatted labels for them
mbavars <- c("vsp3","vsp5","cp17","cp23","leca","salb","sald","etec","cholera","p18","p39","pgp3")

mbalabs <- c("Giardia VSP-3","Giardia VSP-5","Cryptosporidium Cp17","Cryptosporidium Cp23","E. histolytica LecA","Salmonella LPS group B","Salmonella LPS group D","ETEC LT B subunit","Cholera toxin B subunit","Campylobacter p18","Campylobacter p39","C. trachomatis pgp3")

#-----------------------------
# filter to just the relevant
# variables
# rename childid -> id
# Note: there has been some
# attempt at CDC to identify indiv
# children across survey rounds
# using names. This affects a small
# number (n=153). However, some of
# these data appear inconsistent
# based on sex and village,
# so the present analyses will
# simply assume that each measurement
# is a separate child
#-----------------------------
d2 <- d %>% 
  select(svy,year,vilid,clusterid,id=childid,long,seroid,aztr,age,mbavars) %>%
  mutate(id=row_number())


#-----------------------------
# reshape long and convert
# to log10 values
#-----------------------------
dl <- d2 %>%
  gather(antigen,mfi,-svy,-year,-vilid,-clusterid,-seroid,-id,-long,-aztr,-age)

# set negative and zero values to 1 before the log10 transform
dl <- dl %>%
  mutate(mfi = ifelse(mfi<=0,1,mfi),
         logmfi = log10(mfi),
         antigen=factor(antigen,levels=mbavars)
  )

#-----------------------------
# group antigens by pathogen
# for plot aesthetics
# label antigens with fancier names
#-----------------------------
dl$pathogen <- NA
dl$pathogen[dl$antigen %in% c("vsp3","vsp5")] <- "Giardia"
dl$pathogen[dl$antigen %in% c("cp17","cp23")] <- "Cryptosporidium"
dl$pathogen[dl$antigen %in% c("leca")] <- "E. histolytica"
dl$pathogen[dl$antigen %in% c("p18","p39")] <- "Campylobacter"
dl$pathogen[dl$antigen %in% c("salb","sald")] <- "Salmonella"
dl$pathogen[dl$antigen %in% c("etec")] <- "ETEC"
dl$pathogen[dl$antigen %in% c("cholera")] <- "V. cholerae"
dl$pathogen[dl$antigen %in% c("pgp3")] <- "C. trachomatis"


dl <- dl %>%
  mutate(pathogen = factor(pathogen,levels=c("Giardia","Cryptosporidium","E. histolytica","Salmonella","ETEC","V. cholerae","Campylobacter","C. trachomatis")),
         antigenf=factor(antigen,levels=mbavars,labels=mbalabs)) %>%
  select(pathogen,antigen,antigenf,everything(),-long,-seroid)
     
#-----------------------------
# save a long version of the
# dataset for all future 
# analyses
#-----------------------------
saveRDS(dl,file=here::here("data","kongwa_analysis.rds"))
write_csv(dl,path=here::here("data","kongwa_analysis.csv"))

```
# Session Info
```{r session info}
sessionInfo()
```




