---
title: Enteropathogen seroepidemiology among children in low-resource settings
subtitle: Comparison of seroprevalence with seroconversion rates (force of infection) in Haiti and Kenya, Figure 5, including Fig 5 supplement 1
output:
  html_document:
    highlight: haddock
    theme: default
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

# Summary

Create a composite figure that summarizes the relationship between seroconversion rates and seroprevalence in the Kenya and Haiti cohorts. 

# Script preamble
```{r preamble}
#-----------------------------
# preamble
#-----------------------------
library(here)
here()

# load packages
library(tidyverse)
library(viridis)
library(gridExtra)

# set up for parallel computing
# configure for a laptop (use only 3 cores)
library(foreach)
library(doParallel)
registerDoParallel(cores=3)

# bright color blind palette:  https://personal.sron.nl/~pault/ 
cblack <- "#000004FF"
cblue <- "#3366AA"
cteal <- "#11AA99"
cgreen <- "#66AA55"
cchartr <- "#CCCC55"
cmagent <- "#992288"
cred <- "#EE3333"
corange <- "#EEA722"
cyellow <- "#FFEE33"
cgrey <- "#777777"

# viridis color palette
vircols <- viridis(n=4,alpha=1,begin=0.2,end=0.97)

# safe color blind palette
# http://jfly.iam.u-tokyo.ac.jp/color/
# http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```


```{r load estimates}
#-----------------------------
# load the estimates
# created with 
# Fig6-asembo-incidence-analysis.Rmd
# Table2-haiti-incidence-analysis.Rmd
#-----------------------------
dk <- readRDS(here("output","asembo-enteric-ab-ests-seroprev-vs-rates.rds"))
dh <- readRDS(here("output","haiti-enteric-ab-ests-seroprev-vs-rates.rds"))
dha <- readRDS(here("output","haiti-enteric-ab-ests-seroprev-vs-rates-byage.rds"))


#-----------------------------
# bind together and create
# common factor variables
# drop cholera estimates from
# Kenya due to difficulty of 
# interpretation due to cross-
# reactivity with ETEC
#-----------------------------
dk <- dk %>% mutate(country="Kenya")
dh <- dh %>% mutate(country="Haiti")
d <- bind_rows(dk,dh) %>%
  filter(antigenf!="Cholera toxin β subunit") %>%
  mutate(antigenf=factor(antigenf,levels=c("Giardia VSP-3 or VSP-5",
                                           "Cryptosporidium Cp17 or Cp23",
                                           "E. histolytica LecA",
                                           "Salmonella LPS groups B or D",
                                           "ETEC LT β subunit",
                                           "Campylobacter p18 or p39",
                                           "Norovirus GI.4",
                                           "Norovirus GII.4.NO"
                                           )),
         country=factor(country,levels=c("Kenya","Haiti")),
         method=factor(method,levels=c("4-fold increase in MFI","Seropositivity cutoff"),labels=c("seroincidence definition:\n4-fold increase in IgG","seroincidence definition:\ncrossed seropositivity cutoff"))
         )

# 

```



# Composite figure, original scale
```{r rates v seroprevalence2}


# pcols <- c(cred,corange,cgreen,cteal,cblue,cmagent,cchartr,cbPalette[c(8,5)])
pcols <- cbPalette[c(4:1,6:8,5)]

pserop2 <- ggplot(data=d,aes(x=seroprev*100,y=seroi)) +
  geom_pointrange(aes(ymin=seroi_lb,ymax=seroi_ub,color=antigenf)) +
  facet_grid(method~country,scales="free")+
  # scale_x_continuous(breaks=seq(0,1,by=0.1),labels=seq(0,100,by=10))+
  # scale_y_continuous(breaks=0:10)+
  scale_color_manual(values=pcols,guide=guide_legend(title="Pathogen")) +
  # coord_cartesian(xlim=c(0.6,1))+
  labs(x="seroprevalence (%)",y="force of infection\n(seroconversion rate per child-year)")+
  theme_minimal() +
  theme(
     legend.position="right"
  )

pserop2



```

# Separate figures with separate axes

** This is Figure 5 in the manuscript **

```{r separate panels, fig.width=4,fig.height=5}

# Kenya original scale
# order antigens by seroprev + foi 
kd <- d %>% 
  filter(country=="Kenya" & method=="seroincidence definition:\ncrossed seropositivity cutoff") %>%
  mutate(antigeno = factor(antigenf,levels=c("E. histolytica LecA",
                                             "Salmonella LPS groups B or D",
                                             "Giardia VSP-3 or VSP-5",
                                             "Cryptosporidium Cp17 or Cp23",
                                             "ETEC LT β subunit",
                                             "Campylobacter p18 or p39")))

# (colors ordered to be consistent across countries)
pcols <- cbPalette[c(4,6,2,3,7,8)]

pk <- ggplot(data=kd,aes(x=seroprev,y=seroi,color=antigeno,fill=antigeno)) +
  geom_errorbar(aes(ymin=seroi_lb,ymax=seroi_ub),width=0) +
  geom_point(size=2.5,pch=21,color="black") +
  scale_x_continuous(breaks=seq(0,1,by=0.2),labels=seq(0,100,by=20))+
  scale_y_continuous(breaks=0:7)+
  scale_color_manual(values=pcols,guide=FALSE) +
  scale_fill_manual(values=pcols) +
  guides(fill=guide_legend(title="Pathogen", 
                            reverse=TRUE,
                            keywidth=0.15,
                            keyheight=0.15,
                            default.unit="inch",
                            ncol=1))+
  coord_cartesian(xlim=c(0,1),ylim=c(0,7))+
  labs(title="Kenya, ages 4-17 months",x="seroprevalence (%)",y="force of infection\n(seroconversion rate per child-year)")+
  theme_minimal() +
  theme(
     legend.position="right",
     strip.text=element_text(size=12,hjust=0)
  )

# Haiti original scale
# order antigens by seroprev + foi 

hd <- d %>% 
  filter(country=="Haiti" & method=="seroincidence definition:\ncrossed seropositivity cutoff") %>%
  mutate(antigeno = factor(antigenf,levels=c("E. histolytica LecA",
                                             "Giardia VSP-3 or VSP-5",
                                             "Norovirus GI.4",
                                             "Salmonella LPS groups B or D",
                                             "Cryptosporidium Cp17 or Cp23",
                                             "Norovirus GII.4.NO",
                                             "ETEC LT β subunit")))


# (colors ordered to be consistent across countries)
pcols <- cbPalette[c(4,2,5,6,3,8,7)]

ph <- ggplot(data=hd,aes(x=seroprev,y=seroi,color=antigeno,fill=antigeno)) +
  geom_errorbar(aes(ymin=seroi_lb,ymax=seroi_ub),width=0) +
  geom_point(size=2.5,pch=21,color="black") +
  scale_x_continuous(breaks=seq(0.6,1,by=0.1),labels=seq(60,100,by=10))+
  scale_y_continuous(breaks=seq(0,1.5,by=0.5))+
  scale_color_manual(values=pcols,guide=FALSE) +
  scale_fill_manual(values=pcols) +
  guides(fill=guide_legend(title="Pathogen", 
                            reverse=TRUE,
                            keywidth=0.15,
                            keyheight=0.15,
                            default.unit="inch",
                            ncol=1))+
  coord_cartesian(xlim=c(0.6,1),ylim=c(0,1.5))+
  labs(title="Haiti, ages 0 - 11 years",x="seroprevalence (%)",y="force of infection\n(seroconversion rate per child-year)")+
  theme_minimal() +
  theme(
     legend.position="right",
     strip.text=element_text(size=12,hjust=0)
  )

# combined panel
ivsp_composite <- grid.arrange(pk,ph,ncol=1,nrow=2)


# save PDF and TIFF versions
ggsave(file=here("figs","Fig5-asembo-haiti-foi-vs-seroprev.pdf"),plot=ivsp_composite,device=cairo_pdf,height=8,width=6)
ggsave(file=here("figs","Fig5-asembo-haiti-foi-vs-seroprev.TIFF"),plot=ivsp_composite,device="tiff",height=8,width=6)

  
```

# Haiti estimates by age bands

** This is Figure 5 - supplement 1 in the manuscript **
```{r separate panels}

# Haiti, stratified by age bands
# order antigens by seroprev + foi 

dha <- dha %>% 
  mutate(antigeno = factor(antigenf,levels=c("E. histolytica LecA",
                                             "Norovirus GI.4",
                                             "Giardia VSP-3 or VSP-5",
                                             "Salmonella LPS groups B or D",
                                             "Cryptosporidium Cp17 or Cp23",
                                             "Norovirus GII.4.NO",
                                             "ETEC LT β subunit")))


# (colors ordered to be consistent across countries)
pcols <- cbPalette[c(4,5,2,6,3,8,7)]

pha <- ggplot(data=dha,aes(x=seroprev,y=seroi,color=antigeno,fill=antigeno)) +
  facet_grid(~agecat)+
  geom_text(aes(x=0.2,y=2.8,label=nlab),color="gray40")+
  geom_errorbar(aes(ymin=seroi_lb,ymax=seroi_ub),width=0) +
  geom_point(size=2.5,pch=21,color="black") +
  scale_y_continuous(breaks=0:3)+
  scale_x_continuous(breaks=seq(0,1,by=0.2),labels=sprintf("%1.0f",seq(0,1,by=0.2)*100))+
  scale_color_manual(values=pcols,guide=FALSE)+
  scale_fill_manual(values=pcols)+
  labs(x="seroprevalence (%)",y="force of infection\n(seroconversion rate per child-year)")+
  coord_cartesian(xlim=c(0,1),ylim=c(0,3))+
  guides(fill=guide_legend(title="Pathogen", 
                            reverse=TRUE,
                            keywidth=0.15,
                            keyheight=0.15,
                            default.unit="inch",
                            ncol=1))+
  theme_minimal() +
  theme(
     legend.position="right",
     strip.text=element_text(size=12,hjust=0)
  )

# save PDF and TIFF versions
ggsave(file=here("figs","Fig5sup1-haiti-foi-vs-seroprev-byage.pdf"),plot=pha,device=cairo_pdf,height=3,width=11)
ggsave(file=here("figs","Fig5sup1-haiti-foi-vs-seroprev-byage.TIFF"),plot=pha,device="tiff",height=3,width=11)
  
```


# Session Info
```{r session info}
sessionInfo()
```




